/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as MeRouteImport } from './routes/me'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlIndexRouteImport } from './routes/pl/index'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as PlUmiejetnosciRouteImport } from './routes/pl/umiejetnosci'
import { Route as PlStronyInternetoweWarszawaRouteImport } from './routes/pl/strony-internetowe-warszawa'
import { Route as PlProjektyRouteImport } from './routes/pl/projekty'
import { Route as PlProcesRouteImport } from './routes/pl/proces'
import { Route as PlOMnieRouteImport } from './routes/pl/o-mnie'
import { Route as PlKontaktRouteImport } from './routes/pl/kontakt'
import { Route as EnSkillsRouteImport } from './routes/en/skills'
import { Route as EnProjectsRouteImport } from './routes/en/projects'
import { Route as EnProcessRouteImport } from './routes/en/process'
import { Route as EnContactRouteImport } from './routes/en/contact'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as PlUslugiIndexRouteImport } from './routes/pl/uslugi/index'
import { Route as PlBlogIndexRouteImport } from './routes/pl/blog/index'
import { Route as EnServicesIndexRouteImport } from './routes/en/services/index'
import { Route as EnBlogIndexRouteImport } from './routes/en/blog/index'
import { Route as PlUslugiCennikRouteImport } from './routes/pl/uslugi/cennik'
import { Route as PlUslugiSlugRouteImport } from './routes/pl/uslugi/$slug'
import { Route as PlBlogSlugRouteImport } from './routes/pl/blog/$slug'
import { Route as EnServicesPricingRouteImport } from './routes/en/services/pricing'
import { Route as EnServicesSlugRouteImport } from './routes/en/services/$slug'
import { Route as EnBlogSlugRouteImport } from './routes/en/blog/$slug'
import { Route as PlBlogKategoriaSlugRouteImport } from './routes/pl/blog/kategoria.$slug'
import { Route as EnBlogCategorySlugRouteImport } from './routes/en/blog/category.$slug'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlIndexRoute = PlIndexRouteImport.update({
  id: '/pl/',
  path: '/pl/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlUmiejetnosciRoute = PlUmiejetnosciRouteImport.update({
  id: '/pl/umiejetnosci',
  path: '/pl/umiejetnosci',
  getParentRoute: () => rootRouteImport,
} as any)
const PlStronyInternetoweWarszawaRoute =
  PlStronyInternetoweWarszawaRouteImport.update({
    id: '/pl/strony-internetowe-warszawa',
    path: '/pl/strony-internetowe-warszawa',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlProjektyRoute = PlProjektyRouteImport.update({
  id: '/pl/projekty',
  path: '/pl/projekty',
  getParentRoute: () => rootRouteImport,
} as any)
const PlProcesRoute = PlProcesRouteImport.update({
  id: '/pl/proces',
  path: '/pl/proces',
  getParentRoute: () => rootRouteImport,
} as any)
const PlOMnieRoute = PlOMnieRouteImport.update({
  id: '/pl/o-mnie',
  path: '/pl/o-mnie',
  getParentRoute: () => rootRouteImport,
} as any)
const PlKontaktRoute = PlKontaktRouteImport.update({
  id: '/pl/kontakt',
  path: '/pl/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSkillsRoute = EnSkillsRouteImport.update({
  id: '/en/skills',
  path: '/en/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const EnProjectsRoute = EnProjectsRouteImport.update({
  id: '/en/projects',
  path: '/en/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const EnProcessRoute = EnProcessRouteImport.update({
  id: '/en/process',
  path: '/en/process',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/en/contact',
  path: '/en/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PlUslugiIndexRoute = PlUslugiIndexRouteImport.update({
  id: '/pl/uslugi/',
  path: '/pl/uslugi/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlBlogIndexRoute = PlBlogIndexRouteImport.update({
  id: '/pl/blog/',
  path: '/pl/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnServicesIndexRoute = EnServicesIndexRouteImport.update({
  id: '/en/services/',
  path: '/en/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBlogIndexRoute = EnBlogIndexRouteImport.update({
  id: '/en/blog/',
  path: '/en/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlUslugiCennikRoute = PlUslugiCennikRouteImport.update({
  id: '/pl/uslugi/cennik',
  path: '/pl/uslugi/cennik',
  getParentRoute: () => rootRouteImport,
} as any)
const PlUslugiSlugRoute = PlUslugiSlugRouteImport.update({
  id: '/pl/uslugi/$slug',
  path: '/pl/uslugi/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlBlogSlugRoute = PlBlogSlugRouteImport.update({
  id: '/pl/blog/$slug',
  path: '/pl/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnServicesPricingRoute = EnServicesPricingRouteImport.update({
  id: '/en/services/pricing',
  path: '/en/services/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const EnServicesSlugRoute = EnServicesSlugRouteImport.update({
  id: '/en/services/$slug',
  path: '/en/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBlogSlugRoute = EnBlogSlugRouteImport.update({
  id: '/en/blog/$slug',
  path: '/en/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlBlogKategoriaSlugRoute = PlBlogKategoriaSlugRouteImport.update({
  id: '/pl/blog/kategoria/$slug',
  path: '/pl/blog/kategoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBlogCategorySlugRoute = EnBlogCategorySlugRouteImport.update({
  id: '/en/blog/category/$slug',
  path: '/en/blog/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/me': typeof MeRoute
  '/process': typeof ProcessRoute
  '/projects': typeof ProjectsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills': typeof SkillsRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/en/about': typeof EnAboutRoute
  '/en/contact': typeof EnContactRoute
  '/en/process': typeof EnProcessRoute
  '/en/projects': typeof EnProjectsRoute
  '/en/skills': typeof EnSkillsRoute
  '/pl/kontakt': typeof PlKontaktRoute
  '/pl/o-mnie': typeof PlOMnieRoute
  '/pl/proces': typeof PlProcesRoute
  '/pl/projekty': typeof PlProjektyRoute
  '/pl/strony-internetowe-warszawa': typeof PlStronyInternetoweWarszawaRoute
  '/pl/umiejetnosci': typeof PlUmiejetnosciRoute
  '/en/': typeof EnIndexRoute
  '/pl/': typeof PlIndexRoute
  '/en/blog/$slug': typeof EnBlogSlugRoute
  '/en/services/$slug': typeof EnServicesSlugRoute
  '/en/services/pricing': typeof EnServicesPricingRoute
  '/pl/blog/$slug': typeof PlBlogSlugRoute
  '/pl/uslugi/$slug': typeof PlUslugiSlugRoute
  '/pl/uslugi/cennik': typeof PlUslugiCennikRoute
  '/en/blog/': typeof EnBlogIndexRoute
  '/en/services/': typeof EnServicesIndexRoute
  '/pl/blog/': typeof PlBlogIndexRoute
  '/pl/uslugi/': typeof PlUslugiIndexRoute
  '/en/blog/category/$slug': typeof EnBlogCategorySlugRoute
  '/pl/blog/kategoria/$slug': typeof PlBlogKategoriaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/me': typeof MeRoute
  '/process': typeof ProcessRoute
  '/projects': typeof ProjectsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills': typeof SkillsRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/en/about': typeof EnAboutRoute
  '/en/contact': typeof EnContactRoute
  '/en/process': typeof EnProcessRoute
  '/en/projects': typeof EnProjectsRoute
  '/en/skills': typeof EnSkillsRoute
  '/pl/kontakt': typeof PlKontaktRoute
  '/pl/o-mnie': typeof PlOMnieRoute
  '/pl/proces': typeof PlProcesRoute
  '/pl/projekty': typeof PlProjektyRoute
  '/pl/strony-internetowe-warszawa': typeof PlStronyInternetoweWarszawaRoute
  '/pl/umiejetnosci': typeof PlUmiejetnosciRoute
  '/en': typeof EnIndexRoute
  '/pl': typeof PlIndexRoute
  '/en/blog/$slug': typeof EnBlogSlugRoute
  '/en/services/$slug': typeof EnServicesSlugRoute
  '/en/services/pricing': typeof EnServicesPricingRoute
  '/pl/blog/$slug': typeof PlBlogSlugRoute
  '/pl/uslugi/$slug': typeof PlUslugiSlugRoute
  '/pl/uslugi/cennik': typeof PlUslugiCennikRoute
  '/en/blog': typeof EnBlogIndexRoute
  '/en/services': typeof EnServicesIndexRoute
  '/pl/blog': typeof PlBlogIndexRoute
  '/pl/uslugi': typeof PlUslugiIndexRoute
  '/en/blog/category/$slug': typeof EnBlogCategorySlugRoute
  '/pl/blog/kategoria/$slug': typeof PlBlogKategoriaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/me': typeof MeRoute
  '/process': typeof ProcessRoute
  '/projects': typeof ProjectsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills': typeof SkillsRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/en/about': typeof EnAboutRoute
  '/en/contact': typeof EnContactRoute
  '/en/process': typeof EnProcessRoute
  '/en/projects': typeof EnProjectsRoute
  '/en/skills': typeof EnSkillsRoute
  '/pl/kontakt': typeof PlKontaktRoute
  '/pl/o-mnie': typeof PlOMnieRoute
  '/pl/proces': typeof PlProcesRoute
  '/pl/projekty': typeof PlProjektyRoute
  '/pl/strony-internetowe-warszawa': typeof PlStronyInternetoweWarszawaRoute
  '/pl/umiejetnosci': typeof PlUmiejetnosciRoute
  '/en/': typeof EnIndexRoute
  '/pl/': typeof PlIndexRoute
  '/en/blog/$slug': typeof EnBlogSlugRoute
  '/en/services/$slug': typeof EnServicesSlugRoute
  '/en/services/pricing': typeof EnServicesPricingRoute
  '/pl/blog/$slug': typeof PlBlogSlugRoute
  '/pl/uslugi/$slug': typeof PlUslugiSlugRoute
  '/pl/uslugi/cennik': typeof PlUslugiCennikRoute
  '/en/blog/': typeof EnBlogIndexRoute
  '/en/services/': typeof EnServicesIndexRoute
  '/pl/blog/': typeof PlBlogIndexRoute
  '/pl/uslugi/': typeof PlUslugiIndexRoute
  '/en/blog/category/$slug': typeof EnBlogCategorySlugRoute
  '/pl/blog/kategoria/$slug': typeof PlBlogKategoriaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/me'
    | '/process'
    | '/projects'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/skills'
    | '/stats'
    | '/en/about'
    | '/en/contact'
    | '/en/process'
    | '/en/projects'
    | '/en/skills'
    | '/pl/kontakt'
    | '/pl/o-mnie'
    | '/pl/proces'
    | '/pl/projekty'
    | '/pl/strony-internetowe-warszawa'
    | '/pl/umiejetnosci'
    | '/en/'
    | '/pl/'
    | '/en/blog/$slug'
    | '/en/services/$slug'
    | '/en/services/pricing'
    | '/pl/blog/$slug'
    | '/pl/uslugi/$slug'
    | '/pl/uslugi/cennik'
    | '/en/blog/'
    | '/en/services/'
    | '/pl/blog/'
    | '/pl/uslugi/'
    | '/en/blog/category/$slug'
    | '/pl/blog/kategoria/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/me'
    | '/process'
    | '/projects'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/skills'
    | '/stats'
    | '/en/about'
    | '/en/contact'
    | '/en/process'
    | '/en/projects'
    | '/en/skills'
    | '/pl/kontakt'
    | '/pl/o-mnie'
    | '/pl/proces'
    | '/pl/projekty'
    | '/pl/strony-internetowe-warszawa'
    | '/pl/umiejetnosci'
    | '/en'
    | '/pl'
    | '/en/blog/$slug'
    | '/en/services/$slug'
    | '/en/services/pricing'
    | '/pl/blog/$slug'
    | '/pl/uslugi/$slug'
    | '/pl/uslugi/cennik'
    | '/en/blog'
    | '/en/services'
    | '/pl/blog'
    | '/pl/uslugi'
    | '/en/blog/category/$slug'
    | '/pl/blog/kategoria/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/me'
    | '/process'
    | '/projects'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/skills'
    | '/_authenticated/stats'
    | '/en/about'
    | '/en/contact'
    | '/en/process'
    | '/en/projects'
    | '/en/skills'
    | '/pl/kontakt'
    | '/pl/o-mnie'
    | '/pl/proces'
    | '/pl/projekty'
    | '/pl/strony-internetowe-warszawa'
    | '/pl/umiejetnosci'
    | '/en/'
    | '/pl/'
    | '/en/blog/$slug'
    | '/en/services/$slug'
    | '/en/services/pricing'
    | '/pl/blog/$slug'
    | '/pl/uslugi/$slug'
    | '/pl/uslugi/cennik'
    | '/en/blog/'
    | '/en/services/'
    | '/pl/blog/'
    | '/pl/uslugi/'
    | '/en/blog/category/$slug'
    | '/pl/blog/kategoria/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  MeRoute: typeof MeRoute
  ProcessRoute: typeof ProcessRoute
  ProjectsRoute: typeof ProjectsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SkillsRoute: typeof SkillsRoute
  EnAboutRoute: typeof EnAboutRoute
  EnContactRoute: typeof EnContactRoute
  EnProcessRoute: typeof EnProcessRoute
  EnProjectsRoute: typeof EnProjectsRoute
  EnSkillsRoute: typeof EnSkillsRoute
  PlKontaktRoute: typeof PlKontaktRoute
  PlOMnieRoute: typeof PlOMnieRoute
  PlProcesRoute: typeof PlProcesRoute
  PlProjektyRoute: typeof PlProjektyRoute
  PlStronyInternetoweWarszawaRoute: typeof PlStronyInternetoweWarszawaRoute
  PlUmiejetnosciRoute: typeof PlUmiejetnosciRoute
  EnIndexRoute: typeof EnIndexRoute
  PlIndexRoute: typeof PlIndexRoute
  EnBlogSlugRoute: typeof EnBlogSlugRoute
  EnServicesSlugRoute: typeof EnServicesSlugRoute
  EnServicesPricingRoute: typeof EnServicesPricingRoute
  PlBlogSlugRoute: typeof PlBlogSlugRoute
  PlUslugiSlugRoute: typeof PlUslugiSlugRoute
  PlUslugiCennikRoute: typeof PlUslugiCennikRoute
  EnBlogIndexRoute: typeof EnBlogIndexRoute
  EnServicesIndexRoute: typeof EnServicesIndexRoute
  PlBlogIndexRoute: typeof PlBlogIndexRoute
  PlUslugiIndexRoute: typeof PlUslugiIndexRoute
  EnBlogCategorySlugRoute: typeof EnBlogCategorySlugRoute
  PlBlogKategoriaSlugRoute: typeof PlBlogKategoriaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pl/': {
      id: '/pl/'
      path: '/pl'
      fullPath: '/pl/'
      preLoaderRoute: typeof PlIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pl/umiejetnosci': {
      id: '/pl/umiejetnosci'
      path: '/pl/umiejetnosci'
      fullPath: '/pl/umiejetnosci'
      preLoaderRoute: typeof PlUmiejetnosciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pl/strony-internetowe-warszawa': {
      id: '/pl/strony-internetowe-warszawa'
      path: '/pl/strony-internetowe-warszawa'
      fullPath: '/pl/strony-internetowe-warszawa'
      preLoaderRoute: typeof PlStronyInternetoweWarszawaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pl/projekty': {
      id: '/pl/projekty'
      path: '/pl/projekty'
      fullPath: '/pl/projekty'
      preLoaderRoute: typeof PlProjektyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pl/proces': {
      id: '/pl/proces'
      path: '/pl/proces'
      fullPath: '/pl/proces'
      preLoaderRoute: typeof PlProcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pl/o-mnie': {
      id: '/pl/o-mnie'
      path: '/pl/o-mnie'
      fullPath: '/pl/o-mnie'
      preLoaderRoute: typeof PlOMnieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pl/kontakt': {
      id: '/pl/kontakt'
      path: '/pl/kontakt'
      fullPath: '/pl/kontakt'
      preLoaderRoute: typeof PlKontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/skills': {
      id: '/en/skills'
      path: '/en/skills'
      fullPath: '/en/skills'
      preLoaderRoute: typeof EnSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/projects': {
      id: '/en/projects'
      path: '/en/projects'
      fullPath: '/en/projects'
      preLoaderRoute: typeof EnProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/process': {
      id: '/en/process'
      path: '/en/process'
      fullPath: '/en/process'
      preLoaderRoute: typeof EnProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/en/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/pl/uslugi/': {
      id: '/pl/uslugi/'
      path: '/pl/uslugi'
      fullPath: '/pl/uslugi/'
      preLoaderRoute: typeof PlUslugiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pl/blog/': {
      id: '/pl/blog/'
      path: '/pl/blog'
      fullPath: '/pl/blog/'
      preLoaderRoute: typeof PlBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/services/': {
      id: '/en/services/'
      path: '/en/services'
      fullPath: '/en/services/'
      preLoaderRoute: typeof EnServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/blog/': {
      id: '/en/blog/'
      path: '/en/blog'
      fullPath: '/en/blog/'
      preLoaderRoute: typeof EnBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pl/uslugi/cennik': {
      id: '/pl/uslugi/cennik'
      path: '/pl/uslugi/cennik'
      fullPath: '/pl/uslugi/cennik'
      preLoaderRoute: typeof PlUslugiCennikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pl/uslugi/$slug': {
      id: '/pl/uslugi/$slug'
      path: '/pl/uslugi/$slug'
      fullPath: '/pl/uslugi/$slug'
      preLoaderRoute: typeof PlUslugiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pl/blog/$slug': {
      id: '/pl/blog/$slug'
      path: '/pl/blog/$slug'
      fullPath: '/pl/blog/$slug'
      preLoaderRoute: typeof PlBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/services/pricing': {
      id: '/en/services/pricing'
      path: '/en/services/pricing'
      fullPath: '/en/services/pricing'
      preLoaderRoute: typeof EnServicesPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/services/$slug': {
      id: '/en/services/$slug'
      path: '/en/services/$slug'
      fullPath: '/en/services/$slug'
      preLoaderRoute: typeof EnServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/blog/$slug': {
      id: '/en/blog/$slug'
      path: '/en/blog/$slug'
      fullPath: '/en/blog/$slug'
      preLoaderRoute: typeof EnBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pl/blog/kategoria/$slug': {
      id: '/pl/blog/kategoria/$slug'
      path: '/pl/blog/kategoria/$slug'
      fullPath: '/pl/blog/kategoria/$slug'
      preLoaderRoute: typeof PlBlogKategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/blog/category/$slug': {
      id: '/en/blog/category/$slug'
      path: '/en/blog/category/$slug'
      fullPath: '/en/blog/category/$slug'
      preLoaderRoute: typeof EnBlogCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  MeRoute: MeRoute,
  ProcessRoute: ProcessRoute,
  ProjectsRoute: ProjectsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SkillsRoute: SkillsRoute,
  EnAboutRoute: EnAboutRoute,
  EnContactRoute: EnContactRoute,
  EnProcessRoute: EnProcessRoute,
  EnProjectsRoute: EnProjectsRoute,
  EnSkillsRoute: EnSkillsRoute,
  PlKontaktRoute: PlKontaktRoute,
  PlOMnieRoute: PlOMnieRoute,
  PlProcesRoute: PlProcesRoute,
  PlProjektyRoute: PlProjektyRoute,
  PlStronyInternetoweWarszawaRoute: PlStronyInternetoweWarszawaRoute,
  PlUmiejetnosciRoute: PlUmiejetnosciRoute,
  EnIndexRoute: EnIndexRoute,
  PlIndexRoute: PlIndexRoute,
  EnBlogSlugRoute: EnBlogSlugRoute,
  EnServicesSlugRoute: EnServicesSlugRoute,
  EnServicesPricingRoute: EnServicesPricingRoute,
  PlBlogSlugRoute: PlBlogSlugRoute,
  PlUslugiSlugRoute: PlUslugiSlugRoute,
  PlUslugiCennikRoute: PlUslugiCennikRoute,
  EnBlogIndexRoute: EnBlogIndexRoute,
  EnServicesIndexRoute: EnServicesIndexRoute,
  PlBlogIndexRoute: PlBlogIndexRoute,
  PlUslugiIndexRoute: PlUslugiIndexRoute,
  EnBlogCategorySlugRoute: EnBlogCategorySlugRoute,
  PlBlogKategoriaSlugRoute: PlBlogKategoriaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
